name: dl
favicon: null
layout_spectrum: 0.38765304535627365
typography_spectrum: 0.3815502959769219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.38140469253994524
  lightness: 0.6285660283174366
  saturation: 0.9569426437374204
  rhythmicContrast: 0.7956559706944972
purpose: []
